language: node_js
node_js:
  - "node"

cache:
  directories:
  - "$HOME/.npm"
install:
  - npm ci
  - npm --prefix ./functions install
script:
  - npm run build
  - npm --prefix ./functions run lint

deploy:
  provider: firebase
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master