language: node_js
node_js:
  - "node"

cache:
  directories:
    - "$HOME/.npm"
install: npm ci
script: npm run build

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master