language: node_js
node_js:
  - "node"

cache:
  directories:
  - "$HOME/.npm"
install:
  - npm ci
  - npm --prefix ./functions install
script:
  - npm run build
  - npm --prefix ./functions run lint

deploy:
  provider: firebase
  token:
    secure: EG0SaP7qRB5nJBVmj8zqrjot6EN0J0MfcUyhFMqJQxDXUuZ7DwmqUtoX86hhk6LMs4SMyJdkEB7YYeVWPY7usZsbwcSkugkMCv9ADtST6fDlh9493eVUcv+A/5vyV4x0dGVdX9DuJdzO4WevkK/0L6n++G+knlV7e5vZDwfs5nAsnk6gX//QmNIaC+5aeL1vo3QC2rQ4wSmDMO14wMSy2SgoL8r1zNaEeawgrXwSs83JX/wTQyNJH5Kxhgo5VIJ3/1RH8VYed3bef3tR9ciDgWVvwCGVOiAjC7XF5WC0x3krWO3MFNV6D5OUXPz41GR2e5nTEqlzaydduJ3jDBFuutZ1FkFH66Z0YbxpupC99kxJYjrgIYJSkrVPhsvYdMfKG9PwH/jvCWI3XSTRg7fGVy6eoCCIci+iWOadcuJ845/HABXZbVWbPVet44VrXi5TqD/0S1S/aY7HQBXguiveaaitkHVSEdcGh4cygBhgWQCJrgRSNuNoN/vtoOVID1k8MQQGJ6Nbh5s+JrO4/uj3Rzj5ZVtIYobHnLGRQiF4/p3XcTmZKT8oMZnLcUXYdgtSkXMammmlAs1rLvPlF6gADnOHul9OXXR/YwQAYWguvqGiuUnhhOy9+rDjyRnLIRA3rOht/kBB8iyh9TZVJy9gErhKNf2gNoFZ1AJvepGAdQM=
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master